### ISSUE TITLE
Move LICENSE into a LICENSE file

### ISSUE THREAD

**Issue by cbetta** [interfax/interfax-dotnet#1]
This is common practice on Github:

http://choosealicense.com/licenses/mit/

**Comment by if-adam** [comment]
Yes, MIT is already the chosen license for .net.

**Comment by cbetta** [comment]
@if-adam I know, just saying we should move it out of the README and into a LICENSE file

**Comment by cbetta** [comment]
From that URL I shared:


> How to apply this license
> 
> Create a text file (typically named LICENSE or LICENSE.txt) in the root of your source code and copy the text of the license into the file. Replace [year] with the current year and [fullname] with the name (or names) of the copyright holders.
> 
> Optional: Add MIT to your project's package description, if applicable (e.g., Node.js, Ruby, and Rust). This will ensure the license is displayed in package directories.

**Comment by if-adam** [comment]
Yes, agreed.
