### ISSUE TITLE
Make integration tests work with any set of user credentials

### ISSUE THREAD

**Issue by cbetta** [interfax/interfax-dotnet#10]
Currently we are using hard coded fax and document IDs in some places in the integration tests. As a result the tests fail when a different user tries to edit the code and run the tests, as they do not have access to the same resources. 

We should fix this, one way to do this is to "find" a fax ID first based on the whole list of faxes.

**Comment by jdpearce** [comment]
That would be one way to do it, yes. Assuming there are faxes already existing. I can't recall if I left any `Thread.Sleep`s in the tests - these were my way of trying to create outbound faxes from scratch and work with those so we didn't have to rely on anything being present, but there are some methods (such as those on inbound faxes) which can't be tested that way and the delay between faxes being accepted/sent by the API and things like images being available wasn't known or discovered at the time.

**Comment by cbetta** [comment]
The more I think about it, the more I am not sure if these kind of tests make sense. Ideally the tests should only test if the SDK passes the right arguments to the API, and if it parses the API responses correctly when they return. The actual API call returning what is expected is out of scope.

Now obviously there's a few ways to solve this. In Ruby we'd use something like VCR to record responses for certain apI calls: https://github.com/vcr/vcr. This ensures that a) if the request changes the VCR will fail and warn the user that the request changed, and b) it ensures that the responses are parsed as if a real API call was made, without actually doing so.

But to be honest, we didn't do these kind of tests in any of the other SDK, so as it stands I am happy to scrap/mock them out.
