### ISSUE TITLE
Has interfax.SendFax been defined?

### ISSUE THREAD

**Issue by cbetta** [interfax/interfax-dotnet#11]
The README suggests it has, but the code seems to suggest it's only available as `interfax.Outbound.SendFax`.

**Comment by jdpearce** [comment]
D'oh. An oversight on my part - It should be as you say, `interfax.Outbound.SendFax`

**Comment by cbetta** [comment]
Ok then we should update the README.

**Comment by cbetta** [comment]
This has now been fixed.
