### ISSUE TITLE
InfoundFax fails to deserialize if image status is DONT_EXIST

### ISSUE THREAD

**Issue by MattHoneycutt** [interfax/interfax-dotnet#12]
If the Interfax account is configured to remove images after retrieval, then the inbound faxes will have an image status of DONT_EXIST.  The ImageStatus enum does not define this value, so deserialization fails.

**Comment by eyalnevo** [comment]
Hi @MattHoneycutt 
I am very sorry for the delay in getting back to you.
The library has been updated with the relevant image status option. Please download version 1.0.5 of the library and let me know if there are any further issues.
