### ISSUE TITLE
Request - Fax byte[] in addition to files...

### ISSUE THREAD

**Issue by bcallister** [interfax/interfax-dotnet#19]
Please consider supporting FaxClient.Documents.BuildFaxDocument(byte[], ...) in addition to filename and uri building options. We have a need to send from a byte[] directly without the option to be able to write to disk first (which would be unwanted overhead even if we could). Many thanks!

**Comment by kaelanfouwels** [comment]
Sounds good, will update the library to include. Expect it in the new release Monday.

**Comment by sdominInterfax** [comment]
Thank you Kaelan.

**Comment by bcallister** [comment]
You're the man - many thanks!
