### ISSUE TITLE
Fix: InterFAX.Api does not have a strong name...

### ISSUE THREAD

**Issue by bcallister** [interfax/interfax-dotnet#20]
My project complains when building with the InterFAX.Api assembly. Below is the error:

"Referenced assembly 'InterFAX.Api, Version=3.0.1.0, Culture=neutral, PublicKeyToken=null' does not have a strong name."

Can you please resolve this and post an updated version to Nuget? Many thanks.

**Comment by kaelanfouwels** [comment]
Will look in to this and update you.

**Comment by kaelanfouwels** [comment]
Are you code signing your binary/application by any chance?

Nuget currently does not allow signed applications to import unsigned dependencies, which would produce this error.

If you can confirm this is the case, I can look in to getting the InterFAX package signed so you can call it.

CC/ @sdominInterfax

**Comment by bcallister** [comment]
Yes, this is the case. I would assume most devs releasing production software are in the same boat. For example, Windows Store apps require your packages be signed. Many thanks for helping get a signed version of the InterFAX package.

Cheers!

Ben


________________________________

**Comment by sdominInterfax** [comment]
Hi Kaelan,
I am not code signing. Thank you very much for helping with the library.

**Comment by ricky-shake-n-bake-bobby** [comment]
A signed version of client 3.1.4 is now available that should resolve this issue.

**Comment by kaelanfouwels** [comment]
glad we finally fixed this 😂😂
