### ISSUE TITLE
FaxClient should not set default serialization settings

### ISSUE THREAD

**Issue by hackked** [interfax/interfax-dotnet#22]
Any time a FaxClient is created in our application, it overwrites the default serialization settings in Json.Net.  Investigating the code, there is this code block in the constructor that should be removed/reworked:

`            
JsonConvert.DefaultSettings = () =>
            {
                var settings = new JsonSerializerSettings();
settings.Converters.Add(new StringEnumConverter { CamelCaseText = true });
                return settings;
            };
`
This is generally considered a bad practice for any libraries as it interferes with app behavior.

**Comment by kaelanfouwels** [comment]
Agreed, have submitted to the team, will keep you updated.

**Comment by shahzadadil** [comment]
This is an important one. we also encountered this issue for one of the projects. The side effect was once the settings were changed, it broke the whole application. All of the enums on all of the pages were getting translated into string values as opposed to numbers. So every functionality was breaking.
We had to create our own custom client as a workaround for this.

**Comment by kaelanfouwels** [comment]
@eyalnevo

**Comment by sdominInterfax** [comment]
Hi all, can I ask you please which version of Newtonsoft are you using?  The issue may be related to the version.

**Comment by sdominInterfax** [comment]
Hi @hackked, @kaelanfouwels, @shahzadadil  can I ask you please which version of Newtonsoft are you using? The issue may be related to the version. My version is Newtonsoft.Json.11.0.2

The method was obsolete in the latest version https://www.newtonsoft.com/json/help/html/P_Newtonsoft_Json_Converters_StringEnumConverter_CamelCaseText.htm

**Comment by hackked** [comment]
@sdominInterfax I think you are missing the key point on this one.  The library should not set the static JsonConvert.DefaultSettings property anywhere.  If you do, this will overwrite whatever value an end user application may have set previously.

**Comment by ricky-shake-n-bake-bobby** [comment]
This has been resolved in version 3.1.3.
