### ISSUE TITLE
Deploying inside Azure Functions...

### ISSUE THREAD

**Issue by bcallister** [interfax/interfax-dotnet#23]
I am trying to use this SDK within my Azure Functions project. Everything works great when I test on my machine. However, when I deploy my project to Azure (production), I get a runtime error saying that the 'SupportedMediaTypes.json' file is not deployed in the 'bin' folder. Instead, Visual Studio places this file inside the parent '\wwwroot\' folder.

I do not know how to instruct VS to place this file in the '\wwwroot\bin' folder where the 'InterFAX.Api.dll' assembly is located and where this assembly is looking for it. Also, why is this file even necessary? It would be nice if the SDK just supported these types by default, unless overridden by the presence of this file. Alternatively, if I could setup the mappings in code, rather than via this file.

Please help - this is crucial I resolve this issue. Many thanks in advance!

**Comment by kaelanfouwels** [comment]
Looking at the code, this is already the implementation - SupportedMediaTypes.json is built as an embedded resource into the .dll, which can optionally be overridden by placing a file version in the assembly path.

```
InterFAX.Api.csproj

<ItemGroup>
  <EmbeddedResource Include="SupportedMediaTypes.json" />
</ItemGroup>
```

```csharp
Documents.cs

private Dictionary<string, string> _supportedMediaTypes;
public Dictionary<string, string> SupportedMediaTypes
{
    get
    {
        if (_supportedMediaTypes == null)
        {
            var assembly = Assembly.GetAssembly(typeof(Documents));
            var assemblyPath = Path.GetDirectoryName(assembly.Location);
            var typesFile = Path.Combine(assemblyPath, "SupportedMediaTypes.json");

            if (!File.Exists(typesFile))
            {
                // unpack the types file to the assembly path
                using (var resource = assembly.GetManifestResourceStream("InterFAX.Api.SupportedMediaTypes.json"))
                {
                    using (var file = new FileStream(typesFile, FileMode.Create, FileAccess.Write))
                    {
                        resource.CopyTo(file);
                    }
                }
            }

            var mappings = JsonConvert.DeserializeObject<List<MediaTypeMapping>>(File.ReadAllText(typesFile));
            _supportedMediaTypes = mappings.ToDictionary(
                        mapping => mapping.FileType,
                        mapping => mapping.MediaType);
        }
        return _supportedMediaTypes;
    }
}
```
