### ISSUE TITLE
InboundFax.MessageId datatype is inconsistent API

### ISSUE THREAD

**Issue by lancekeas** [interfax/interfax-dotnet#5]
InboundFax.MessageId is a string, but all other operations against an InboundFax require fax identification by integer. 

Working with the API while processing the inbound queue requires integer parsing to complete the cycle of Inbound.GetList, GetFaxImageStream, MarkAsRead.

**Comment by eyalnevo** [comment]
Thank you for notifying us of this issue, @lancekeas 
It would seem there is an incorrect definition of the InboundFax object that we need to correct.

We will make the necessary adjustments and I will advise once completed and a new version is available.
