### ISSUE TITLE
Outbound.GetCompleted does not include ids

### ISSUE THREAD

**Issue by lancekeas** [interfax/interfax-dotnet#7]
Outbound.GetCompleted does not include ids when making web request.

**Comment by eyalnevo** [comment]
@jdpearce Can you please look at this issue? It seems that the object of "OutboundFaxSummary" does nt include the transaction ID.

**Comment by eyalnevo** [comment]
Hi @lancekeas, I am sorry for the delay in getting back to you. There was an issue with the library code for the GetCompleted method where it was not using the provided fax IDs.
We have corrected the version and if you downloaded the latest version of the library, it should work better.

**Comment by lancekeas** [comment]
Thank you!
