### ISSUE TITLE
Add instructions on how to run tests

### ISSUE THREAD

**Issue by cbetta** [interfax/interfax-dotnet#9]
I'd like to add some instructions to the [Contributing](https://github.com/interfax/interfax-dotnet#contributing) section on how to exactly run the tests. This will be useful to anyone trying to add bug fixes.

**Comment by jdpearce** [comment]
Basically you need this - https://marketplace.visualstudio.com/items?itemName=NUnitDevelopers.NUnit3TestAdapter
